# Generated by Django 5.2.5 on 2025-08-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('original_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('image', models.URLField()),
                ('s_description', models.TextField(max_length=500)),
                ('l_description', models.TextField(blank=True)),
                ('trending', models.BooleanField(default=False)),
                ('tags', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
