# Generated by Django 5.2.5 on 2025-09-01 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('favicon', models.FileField(upload_to='static/uploads/')),
                ('logo', models.FileField(upload_to='static/uploads/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(14)])),
                ('address', models.CharField(max_length=1000)),
                ('fb_link', models.URLField(blank=True)),
                ('insta_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
            ],
        ),
    ]
