# Generated by Django 5.2.5 on 2025-09-14 10:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_size'),
        ('userpage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_no', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(14)])),
                ('address', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD')], max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
